{% set name = "pyinterpolate" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyinterpolate-{{ version }}.tar.gz
  sha256: 4c860f662a7c2765b3b5c0b82d597619bf53506baaf47c295fc9064b744d6b14

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - tqdm
    - descartes
    - prettytable
    - rtree
    - pyogrio
    - geopandas
    - pandas
    - scipy
    - dask-core
    - numpy
    - matplotlib-base
    - shapely
    - pyarrow
    - pylibtiff >=0.6.1
    - deprecation

test:
  imports:
    - pyinterpolate

about:
  home: https://github.com/DataverseLabs/pyinterpolate
  summary: Spatial Interpolation in Python
  dev_url: https://github.com/DataverseLabs/pyinterpolate
  license: BSD-3-Clause
  license_file: license.txt

extra:
  recipe-maintainers:
    - SimonMolinsky
