{% set name = "pyinterpolate" %}
{% set version = "0.5.0.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyinterpolate-{{ version }}.tar.gz
  sha256: ed9e309ca2de8c51b830da637c35506e9fa6bfa9aa9c5c16186a61358b54ea4e

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - tqdm
    - descartes
    - prettytable
    - rtree
    - pyogrio
    - geopandas
    - pandas
    - scipy
    - dask-core
    - numpy
    - matplotlib-base
    - shapely
    - hdbscan ==0.8.33
    - pyarrow
    - pylibtiff ==0.5.1

test:
  imports:
    - pyinterpolate

about:
  home: https://github.com/DataverseLabs/pyinterpolate
  summary: Spatial Interpolation in Python
  dev_url: https://github.com/DataverseLabs/pyinterpolate
  license: BSD-3-Clause
  license_file: license.txt

extra:
  recipe-maintainers:
    - SimonMolinsky
